### ISSUE TITLE
Alta de invitaciones 

### ISSUE THREAD

**Issue by angelsalvadormx** [colxsoft-com/Invitaciones_front#34]
Alinear el boton con el titulo, el margen superior e inferior debe ser el mismo
![image](https://github.com/colxsoft-com/Invitaciones_front/assets/36232940/b40c9a74-d6ca-4216-9ab6-b987f2ca035d)

**Comment by PaAdRaAg** [comment]
Ya se soluci´onó en issues anteriores.
